############# English navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "À propos"
url = "/about"
weight = 2

[[main]]
name = "Nos services"
url = "/#our-services-section"
weight = 3

#[[main]]
#name = "Elements"
#url = "/elements"
#weight = 3

[[main]]
name = "Nous contacter"
url = "/contact"
weight = 3

#[[main]]
#weight = 4
#name = "Pages"

#[[main]]
#parent = "Pages"
#name = "Blog"
#url = "/blog"

#[[main]]
#parent = "Pages"
#name = "Authors"
#url = "/authors"

#[[main]]
#parent = "Pages"
#name = "Categories"
#url = "/categories"

#[[main]]
#parent = "Pages"
#name = "404 Page"
#url = "/404"

###
[[main]]
parent = "Postulez"
name = "Front-End"
url = "/front-end"

[[main]]
parent = "Postulez"
name = "Back-End"
url = "/back-end"

[[main]]
parent = "Postulez"
name = "Data Analyst"
url = "/data-scientist"

[[main]]
parent = "Nos réalisations"
name = "Télémédecine"
url = "/telemedecine"

[[main]]
parent = "Nos réalisations"
name = "Assurance en ligne"
url = "/assurance-en-ligne"

[[main]]
parent = "Nos réalisations"
name = "Estimation des biens immobiliers"
url = "/estimation-des-biens-immobiliers"


###


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
